# Default values for website.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

containers:
  nginx:
    repository: nginx
    tag: stable
    pullPolicy: IfNotPresent
    resources: {}
  website:
    repository: gcr.io/nightguide-infra/website
    tag: 1.0.0
    pullPolicy: IfNotPresent
    resources: {}

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: []

nodeSelector: {}

tolerations: []

affinity: {}
